name: usb_serial
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Bridges-Code/usb_serial

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  freezed:
  build_runner:
